### ISSUE TITLE
.HEIC images support?

### ISSUE THREAD

**Issue by KirillSBarsukov** [calvintwr/blitz-hermite-resize#2]
Hi there!
Is there any way to add .heic support ?

**Comment by calvintwr** [comment]
@KirillSBarsukov It is possible to incorporate a library like [Heic2any][https://github.com/alexcorvi/heic2any] (this guy is a hefty 1.16mb) to convert the file into a lossless png for example, and then feed the result through to blitz.

The reason is because there is no native browser support for HEIC, so a separate library is required to do the conversion.

Even if I add "native" support for blitz, it will work exactly the same.

I could add this into blitz but it will likely have to be a separate module. I can't quite remember what's the best way to do this.
